Phitron/Semester 3/3. Software Development/2. Django/Conceptual Session 3-2/notebook_project/notebook_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls'))
]

Phitron/Semester 3/3. Software Development/2. Django/Conceptual Session 3-2/notebook_project/notes/urls.py
from django.urls import path, include
from . import views

app_name = "notes"

urlpatterns = [
    path('home/', views.index, name='index'),
    path('notes/', views.notes, name='notes'),
    path('note/<int:note_id>', views.note, name='note'),
]

Phitron/Semester 3/3. Software Development/2. Django/Conceptual Session 3-2/notebook_project/notes/views.py
from django.shortcuts import render

myNotes = [{'id': 1, 'title': 'first note', 'entries': ['Entry 1.1', 'Entry 1.2,', 'Entry 1.3']},
           {'id': 2, 'title': 'second note', 'entries': ['Entry 2.1', 'Entry 2.2,', 'Entry 2.3']},
           {'id': 3, 'title': 'third note', 'entries': ['Entry 3.1', 'Entry 3.2,', 'Entry 3.3']},
           ]

def index(request):
    return render(request, 'notes/index.html')

def notes(request):
    notes = myNotes
    context = {'notes': notes}

    return render(request, 'notes/notes.html', context)

def note(request, note_id):
    

Phitron/Semester 3/3. Software Development/2. Django/Conceptual Session 3-2/notebook_project/notes/templates/notes/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title> NoteBook </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'notes:index' %}">
            NoteBook</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'notes:index' %}">
                        Notes</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'notes:index' %}">Register</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'notes:index' %}">Log In</a>
                </li>

                
            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}
            {% endblock page_header %}
        </div>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </main>


    <!-- Scripts File Connection -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

</html>

Phitron/Semester 3/3. Software Development/2. Django/Conceptual Session 3-2/notebook_project/notes/templates/notes/index.html
{% extends "notes/base.html" %}

{% block page_header %}
    <div>
        <h1> Make note of everything here </h1>
        <p> Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note Make Note </p>
    </div>
{% endblock page_header %}

Phitron/Semester 3/3. Software Development/2. Django/Conceptual Session 3-2/notebook_project/notes/templates/notes/notes.html
{% extends 'notes/base.html' %}

{% block page_header %}
    <h1> Notes </h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for note in notes %}
            <li>
                <h3>
                    <a href="{% url 'notes:index' %}">{{note.title}}</a>
                </h3>
            </li>
        {% empty %}
            <h3> No notes there </h3>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'notes:index' %}"></a></h3>

{% endblock content %}